# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdevTest',
                'doc_host': 'https://ML-MG.github.io',
                'git_url': 'https://github.com/ML-MG/nbdevTest',
                'lib_path': 'nbdevTest'},
  'syms': {'nbdevTest.nbdevTest': {'nbdevTest.nbdevTest.foo2': ('nbdevtest.html#foo2', 'nbdevTest/nbdevTest.py')}}}
