"""Fill desc2"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_nbdevTest2.ipynb.

# %% auto 0
__all__ = ['foo2', 'bar2']

# %% ../nbs/01_nbdevTest2.ipynb 3
def foo2(): pass

# %% ../nbs/01_nbdevTest2.ipynb 4
def bar2(): pass
