"""Fill desc"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_nbdevTest.ipynb.

# %% auto 0
__all__ = ['foo1', 'bar1']

# %% ../nbs/00_nbdevTest.ipynb 3
def foo1(): pass

# %% ../nbs/00_nbdevTest.ipynb 4
def bar1(): pass
