"""Fill desc"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_nbdevTest.ipynb.

# %% auto 0
__all__ = ['foo2', 'bar']

# %% ../nbs/00_nbdevTest.ipynb 3
def foo2(): pass

# %% ../nbs/00_nbdevTest.ipynb 4
def bar(): pass
